#公共配置
server:
    port: 8080
    tomcat:
      uri-encoding: UTF-8

spring:
    aop:
      proxy-target-class: true
    datasource:
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        maximum-pool-size: 30
    mvc:
      static-path-pattern: /static/**

#mybatisPlu
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: SpringBoot_MybatisPlus.bean
  global-config:
    #刷新mapper
    refresh-mapper: true
    table-prefix: tbl_
    #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
    id-type: 0
    #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
  #原生配置
  configuration:
    #开启驼峰功能
    map-underscore-to-camel-case: true
    cache-enabled: false
#日志
logging:
  config: classpath:logback.xml
  path: E:\MrHuang\IDEA\springboot_thymeleaf_mybatisplus_shiro_jquery_ajax\LOG_PATH_IS_UNDEFINED




