spring:
  application:
    name: rabbitmq-direct-consumer
  rabbitmq:
    host: 192.168.1.187
    port: 5672
    username: guest
    password: guest

#设置交换机的名称
mq.config.exchange: log.direct
#设置info队列的名称
mq.config.queue.info: log.info
#设置info队列的路由键
mq.config.queue.info.routing.key: log.info.routing.key
#设置error队列名称
mq.config.queue.error: log.error
#设置error队列路由键
mq.config.queue.error.routing.key: log.error.routing.key
