spring:
  application:
    name: rabbitmq-topic-consumer
  rabbitmq:
    host: 192.168.1.187
    port: 5672
    username: guest
    password: guest


#设置交换器的名称
mq.config.exchange: log.topic
#info队列的名称
mq.config.queue.info: log.info
#error队列的名称
mq.config.queue.error: log.error
#log队列的名称
mq.config.queue.logs: log.all